# Generated by Django 5.1.6 on 2025-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=300)),
                ('offer_title', models.TextField()),
                ('offer_price', models.CharField(max_length=100)),
                ('offer_product_link', models.TextField()),
                ('offer_image', models.FileField(upload_to='media/sliderImage/')),
            ],
        ),
    ]
